### ISSUE TITLE
Do you plan to implement upsertRecord?

### ISSUE THREAD

**Issue by abetomo** [kintone/kintone-java-client#11]
https://github.com/kintone-labs/kintone-java-sdk

The Java SDK had an upsertRecord.
Do you plan to implement similar feature?

**Comment by aoking** [comment]
We don't plan to implement upsert at this time.
If there are many requests for it, we will implement it.
Thank you for your comments.

**Comment by abetomo** [comment]
Thanks for the reply.
Would you mind if I implement upsertRecord with reference to [kintone-java-sdk](https://github.com/kintone-labs/kintone-java-sdk)?

**Comment by aoking** [comment]
kintone-java-sdk is of low quality and is not recommended to be used as a reference.
Currently, please implement upsertRecord on the client side.

**Comment by abetomo** [comment]
OK.
