### ISSUE TITLE
getRecordsByCursor実行時にJsonMappingExceptionが発生

### ISSUE THREAD

**Issue by nkcmtr** [kintone/kintone-java-client#37]
### 概要
取得対象のレコードに計算フィールド（日付形式）が含まれている状態でKintoneClient.record().getRecordsByCursorを実行するとJsonMappingExceptionが発生します。

### 再現手順
1. KintoneClient.record().createCursor実行時の引数「field」に計算フィールド（日付形式）を含める。
2. .record().getRecordsByCursorを実行する。

### スタック
com.fasterxml.jackson.databind.JsonMappingException: Character - is neither a decimal digit number, decimal point, nor "e" notation exponential mark. (through reference chain: com.kintone.client.api.record.GetRecordsByCursorResponseBody["records"]->java.util.ArrayList[0])

### バージョン
1.0.2

**Comment by tomohiro-okuyama** [comment]
@nkcmtr 
We have fixed an issue that the client fails to deserialize Calculated fields having the string value of Date, DateTime, or Time. Could you please check if it is reproducible using version 1.4.0?
https://github.com/kintone/kintone-java-client/releases/tag/v1.4.0
Thank you for your report!
